services:
  server:
    build: ./server
    container_name: gastos-server
    ports:
      - "3000:3000"
    volumes:
      - ./expenses.db:/app/expenses.db
    restart: always

  client:
    build: ./client
    container_name: gastos-client
# Removing ports to allow Caddy handle HTTPS
#    ports:
#      - "80:80"
    depends_on:
      - server
    restart: always

  caddy:
    image: caddy:2-alpine
    container_name: gastos-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN:gastosfeli.marrau.ar
    command: caddy reverse-proxy --from https://gastosfeli.marrau.ar --to gastos-client:80

volumes:
  caddy_data:
  caddy_config:
